name: Minigames
main: io.github.lucemans.main.Main
version: 0.1
commands:
   imr:
      description: .
      usage: /imr [player] [cause]
   ready:
      description: .
      usage: /ready
   imjoin:
      description: .
      usage: /imjoin
   imcreateworld:
      description: .
      usage: /imjoin
   imunloadworld:
      description: .
      usage: /imjoin
   lobby:
      description: .
      usage: /lobby
   econ:
      description: .
      usage: /econ
   imvision:
      description: .
      usage: /imvision
   bypass:
      description: .
      usage: /bypass