name: Minigames
main: io.github.lucemans.main.Main
version: 0.1
commands:
   imr:
      description: .
      usage: /imr [player] [cause]
      permission: immortalized.imr
      permission-message: You don't have <permission>
   im:
      description: .
      usage: /im
      permission: immortalized.im
      permission-message: You don't have <permission>
   imjoin:
      description: .
      usage: /imjoin
      permission: immortalized.imjoin
      permission-message: You don't have <permission>
   imcreateworld:
      description: .
      usage: /imjoin
      permission: immortalized.imjoin
      permission-message: You don't have <permission>
   imunloadworld:
      description: .
      usage: /imjoin
      permission: immortalized.imjoin
      permission-message: You don't have <permission>